import Head from 'next/head';
import Footer from './Footer';
import Header from './Header';
//Wrapper-Komponente für eigentlichen Seiteninhalt
export default function Layout({ title, children }) {
  return (
    <div className="site-wrapper" lang="de">
      <Head>
        <title>{title || 'NextJS'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="site-main inner-width">
        {title && <h1>{title}</h1>}
        {children}
      </main>
      <Footer></Footer>
    </div>
  );
}
